### PR TITLE
Maybe a good fix

### PR DESCRIPTION
**Pull request by PedanticHacker**
I have fixed a part of player.py code where you're comparing instances of 2 objects. You used ==, and I propose the isinstance() Python's built-in method.

### CODE REVIEW

**Comment by TurBoss** [comment]
I get this error:

```
Traceback (most recent call last):
  File "C:/cygwin64/home/Jauria/Proyectos/SM/soulmaster/main.py", line 119, in <module>
    main()
  File "C:/cygwin64/home/Jauria/Proyectos/SM/soulmaster/main.py", line 116, in main
    menu.run()
  File "C:\cygwin64\home\Jauria\Proyectos\SM\soulmaster\menu.py", line 119, in run
    self.launch_game()
  File "C:\cygwin64\home\Jauria\Proyectos\SM\soulmaster\menu.py", line 138, in launch_game
    game.run()
  File "C:\cygwin64\home\Jauria\Proyectos\SM\soulmaster\game.py", line 191, in run
    self.update(player_pos, motion_type, facing, min(elapsed_time, MAX_FRAME_TIME))
  File "C:\cygwin64\home\Jauria\Proyectos\SM\soulmaster\game.py", line 97, in update
    self.player.update(motion_type, facing, elapsed_time)
  File "C:\cygwin64\home\Jauria\Proyectos\SM\soulmaster\player.py", line 88, in update
    if isinstance(self.motion_type, MotionType.CASTING) and (self.frame_index >= 29):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by PedanticHacker** [comment]
Then the MotionType.CASTING is not a class type and can't be compared with self.motion_type by using isinstance(). Please revert this back to the original: **if self.motion_type == MotionType.CASTING**

**Comment by TurBoss** [comment]
I can just close the issue

**Comment by PedanticHacker** [comment]
Cool. ;)

**Pull request closed without merging**
